//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public int ID { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public Nullable<int> ID_TRABAJADOR { get; set; }
    
        public virtual TRABAJADOR TRABAJADOR { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
