//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRABAJADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRABAJADOR()
        {
            this.EMPRESA = new HashSet<EMPRESA>();
        }
    
        public int ID { get; set; }
        public string CURP { get; set; }
        public string NSS { get; set; }
        public string SUELDO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string DOMICILIO { get; set; }
        public string OBSERVACION { get; set; }
        public string EDAD { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPRESA> EMPRESA { get; set; }
    }
}
